#!/bin/bash
if [ -d "$1" ] ; then
    HOST_FOLDER=$1
else
    HOST_FOLDER="`pwd`/notebooks";
fi

docker run -v $HOST_FOLDER:/home/ipy/ipynotebooks:rw -p 8888:8888 -p 9001:9001 -i -t ipython /bin/bash
